"""
Complete New Jersey ZIP Code Database - All 576 ZIP codes from user's CSV
This is the authoritative list with accurate city/county mappings
"""

# All 576 NJ ZIP codes from user's CSV data
FULL_NJ_ZIP_LIST = [
    {"zip": "08701", "city": "Lakewood", "county": "Ocean County"},
    {"zip": "07305", "city": "Jersey City", "county": "Hudson County"},
    {"zip": "07002", "city": "Bayonne", "county": "Hudson County"},
    {"zip": "07055", "city": "Passaic", "county": "Passaic County"},
    {"zip": "07087", "city": "Union City", "county": "Hudson County"},
    {"zip": "08753", "city": "Toms River", "county": "Ocean County"},
    {"zip": "07093", "city": "West New York", "county": "Hudson County"},
    {"zip": "07047", "city": "North Bergen", "county": "Hudson County"},
    {"zip": "07111", "city": "Irvington", "county": "Essex County"},
    {"zip": "08854", "city": "Piscataway", "county": "Middlesex County"},
    {"zip": "07030", "city": "Hoboken", "county": "Hudson County"},
    {"zip": "08861", "city": "Perth Amboy", "county": "Middlesex County"},
    {"zip": "08527", "city": "Jackson", "county": "Ocean County"},
    {"zip": "07083", "city": "Union", "county": "Union County"},
    {"zip": "07728", "city": "Freehold", "county": "Monmouth County"},
    {"zip": "08901", "city": "New Brunswick", "county": "Middlesex County"},
    {"zip": "07105", "city": "Newark", "county": "Essex County"},
    {"zip": "07104", "city": "Newark", "county": "Essex County"},
    {"zip": "08873", "city": "Somerset", "county": "Somerset County"},
    {"zip": "07306", "city": "Jersey City", "county": "Hudson County"},
    {"zip": "07470", "city": "Wayne", "county": "Passaic County"},
    {"zip": "08831", "city": "Monroe Township", "county": "Middlesex County"},
    {"zip": "07302", "city": "Jersey City", "county": "Hudson County"},
    {"zip": "07003", "city": "Bloomfield", "county": "Essex County"},
    {"zip": "07304", "city": "Jersey City", "county": "Hudson County"},
    {"zip": "08081", "city": "Sicklerville", "county": "Camden County"},
    {"zip": "08816", "city": "East Brunswick", "county": "Middlesex County"},
    {"zip": "08540", "city": "Princeton", "county": "Mercer County"},
    {"zip": "07052", "city": "West Orange", "county": "Essex County"},
    {"zip": "08817", "city": "Edison", "county": "Middlesex County"},
    {"zip": "08021", "city": "Clementon", "county": "Camden County"},
    {"zip": "07060", "city": "Plainfield", "county": "Union County"},
    {"zip": "08302", "city": "Bridgeton", "county": "Cumberland County"},
    {"zip": "08053", "city": "Marlton", "county": "Burlington County"},
    {"zip": "07960", "city": "Morristown", "county": "Morris County"},
    {"zip": "08234", "city": "Egg Harbor Township", "county": "Atlantic County"},
    {"zip": "07601", "city": "Hackensack", "county": "Bergen County"},
    {"zip": "07036", "city": "Linden", "county": "Union County"},
    {"zip": "08054", "city": "Mount Laurel", "county": "Burlington County"},
    {"zip": "07726", "city": "Englishtown", "county": "Monmouth County"},
    {"zip": "07202", "city": "Elizabeth", "county": "Union County"},
    {"zip": "08360", "city": "Vineland", "county": "Cumberland County"},
    {"zip": "08844", "city": "Hillsborough", "county": "Somerset County"},
    {"zip": "08902", "city": "North Brunswick", "county": "Middlesex County"},
    {"zip": "07307", "city": "Jersey City", "county": "Hudson County"},
    {"zip": "07107", "city": "Newark", "county": "Essex County"},
    {"zip": "07666", "city": "Teaneck", "county": "Bergen County"},
    {"zip": "07032", "city": "Kearny", "county": "Hudson County"},
    {"zip": "08094", "city": "Williamstown", "county": "Gloucester County"},
    {"zip": "08724", "city": "Brick", "county": "Ocean County"},
    {"zip": "08857", "city": "Old Bridge", "county": "Middlesex County"},
    {"zip": "08012", "city": "Blackwood", "county": "Camden County"},
    {"zip": "07011", "city": "Clifton", "county": "Passaic County"},
    {"zip": "07024", "city": "Fort Lee", "county": "Bergen County"},
    {"zip": "07731", "city": "Howell", "county": "Monmouth County"},
    {"zip": "08820", "city": "Edison", "county": "Middlesex County"},
    {"zip": "07017", "city": "East Orange", "county": "Essex County"},
    {"zip": "07712", "city": "Asbury Park", "county": "Monmouth County"},
    {"zip": "08618", "city": "Trenton", "county": "Mercer County"},
    {"zip": "08401", "city": "Atlantic City", "county": "Atlantic County"},
    {"zip": "08807", "city": "Bridgewater", "county": "Somerset County"},
    {"zip": "08080", "city": "Sewell", "county": "Gloucester County"},
    {"zip": "07109", "city": "Belleville", "county": "Essex County"},
    {"zip": "07753", "city": "Neptune", "county": "Monmouth County"},
    {"zip": "07106", "city": "Newark", "county": "Essex County"},
    {"zip": "08096", "city": "Woodbury", "county": "Gloucester County"},
    {"zip": "07501", "city": "Paterson", "county": "Passaic County"},
    {"zip": "08757", "city": "Toms River", "county": "Ocean County"},
    {"zip": "07103", "city": "Newark", "county": "Essex County"},
    {"zip": "08332", "city": "Millville", "county": "Cumberland County"},
    {"zip": "07410", "city": "Fair Lawn", "county": "Bergen County"},
    {"zip": "08016", "city": "Burlington", "county": "Burlington County"},
    {"zip": "08759", "city": "Manchester Township", "county": "Ocean County"},
    {"zip": "07050", "city": "Orange", "county": "Essex County"},
    {"zip": "07840", "city": "Hackettstown", "county": "Warren County"},
    {"zip": "07747", "city": "Matawan", "county": "Middlesex County"},
    {"zip": "07208", "city": "Elizabeth", "county": "Union County"},
    {"zip": "07026", "city": "Garfield", "county": "Bergen County"},
    {"zip": "08723", "city": "Brick", "county": "Ocean County"},
    {"zip": "08610", "city": "Trenton", "county": "Mercer County"},
    {"zip": "07740", "city": "Long Branch", "county": "Monmouth County"},
    {"zip": "08046", "city": "Willingboro", "county": "Burlington County"},
    {"zip": "08611", "city": "Trenton", "county": "Mercer County"},
    {"zip": "08648", "city": "Lawrence Township", "county": "Mercer County"},
    {"zip": "08003", "city": "Cherry Hill", "county": "Camden County"},
    {"zip": "08822", "city": "Flemington", "county": "Hunterdon County"},
    {"zip": "07039", "city": "Livingston", "county": "Essex County"},
    {"zip": "08043", "city": "Voorhees", "county": "Camden County"},
    {"zip": "07090", "city": "Westfield", "county": "Union County"},
    {"zip": "08865", "city": "Phillipsburg", "county": "Warren County"},
    {"zip": "07054", "city": "Parsippany", "county": "Morris County"},
    {"zip": "07206", "city": "Elizabethport", "county": "Union County"},
    {"zip": "08075", "city": "Riverside", "county": "Burlington County"},
    {"zip": "08330", "city": "Mays Landing", "county": "Atlantic County"},
    {"zip": "07013", "city": "Clifton", "county": "Passaic County"},
    {"zip": "07110", "city": "Nutley", "county": "Essex County"},
    {"zip": "07065", "city": "Rahway", "county": "Union County"},
    {"zip": "08520", "city": "Hightstown", "county": "Mercer County"},
    {"zip": "07018", "city": "East Orange", "county": "Essex County"},
    {"zip": "07631", "city": "Englewood", "county": "Bergen County"},
    {"zip": "08055", "city": "Medford", "county": "Burlington County"},
    {"zip": "08755", "city": "Toms River", "county": "Ocean County"},
    {"zip": "08205", "city": "Absecon", "county": "Atlantic County"},
    {"zip": "07920", "city": "Basking Ridge", "county": "Somerset County"},
    {"zip": "07621", "city": "Bergenfield", "county": "Bergen County"},
    {"zip": "07748", "city": "Middletown", "county": "Monmouth County"},
    {"zip": "07201", "city": "Elizabeth", "county": "Union County"},
    {"zip": "07108", "city": "Newark", "county": "Essex County"},
    {"zip": "07424", "city": "Little Falls", "county": "Passaic County"},
    {"zip": "07112", "city": "Newark", "county": "Essex County"},
    {"zip": "08050", "city": "Manahawkin", "county": "Ocean County"},
    {"zip": "07675", "city": "Westwood", "county": "Bergen County"},
    {"zip": "07042", "city": "Montclair", "county": "Essex County"},
    {"zip": "08105", "city": "Camden", "county": "Camden County"},
    {"zip": "07652", "city": "Paramus", "county": "Bergen County"},
    {"zip": "07801", "city": "Dover", "county": "Morris County"},
    {"zip": "07860", "city": "Newton", "county": "Sussex County"},
    {"zip": "07006", "city": "Caldwell", "county": "Essex County"},
    {"zip": "07869", "city": "Randolph", "county": "Morris County"},
    {"zip": "07450", "city": "Ridgewood", "county": "Bergen County"},
    {"zip": "07644", "city": "Lodi", "county": "Bergen County"},
    {"zip": "08005", "city": "Barnegat", "county": "Ocean County"},
    {"zip": "07010", "city": "Cliffside Park", "county": "Bergen County"},
    {"zip": "08060", "city": "Mount Holly", "county": "Burlington County"},
    {"zip": "07430", "city": "Mahwah", "county": "Bergen County"},
    {"zip": "07040", "city": "Maplewood", "county": "Essex County"},
    {"zip": "07701", "city": "Red Bank", "county": "Monmouth County"},
    {"zip": "08742", "city": "Point Pleasant Beach", "county": "Ocean County"},
    {"zip": "07008", "city": "Carteret", "county": "Middlesex County"},
    {"zip": "08087", "city": "Tuckerton", "county": "Ocean County"},
    {"zip": "07076", "city": "Scotch Plains", "county": "Union County"},
    {"zip": "08859", "city": "Parlin", "county": "Middlesex County"},
    {"zip": "08028", "city": "Glassboro", "county": "Gloucester County"},
    {"zip": "07901", "city": "Summit", "county": "Union County"},
    {"zip": "07080", "city": "South Plainfield", "county": "Middlesex County"},
    {"zip": "08088", "city": "Vincentown", "county": "Burlington County"},
    {"zip": "07016", "city": "Cranford", "county": "Union County"},
    {"zip": "08638", "city": "Trenton", "county": "Mercer County"},
    {"zip": "08109", "city": "Merchantville", "county": "Camden County"},
    {"zip": "07724", "city": "Eatontown", "county": "Monmouth County"},
    {"zip": "07508", "city": "Haledon", "county": "Passaic County"},
    {"zip": "08002", "city": "Cherry Hill", "county": "Camden County"},
    {"zip": "08619", "city": "Trenton", "county": "Mercer County"},
    {"zip": "08037", "city": "Hammonton", "county": "Atlantic County"},
    {"zip": "08876", "city": "Somerville", "county": "Somerset County"},
    {"zip": "08879", "city": "South Amboy", "county": "Middlesex County"},
    {"zip": "07203", "city": "Roselle", "county": "Union County"},
    {"zip": "07866", "city": "Rockaway", "county": "Morris County"},
    {"zip": "07522", "city": "Paterson", "county": "Passaic County"},
    {"zip": "07071", "city": "Lyndhurst", "county": "Bergen County"},
    {"zip": "07205", "city": "Hillside", "county": "Union County"},
    {"zip": "08721", "city": "Bayville", "county": "Ocean County"},
    {"zip": "07719", "city": "Belmar", "county": "Monmouth County"},
    {"zip": "07029", "city": "Harrison", "county": "Hudson County"},
    {"zip": "07950", "city": "Morris Plains", "county": "Morris County"},
    {"zip": "08104", "city": "Camden", "county": "Camden County"},
    {"zip": "07094", "city": "Secaucus", "county": "Hudson County"},
    {"zip": "08085", "city": "Swedesboro", "county": "Gloucester County"},
    {"zip": "07751", "city": "Morganville", "county": "Monmouth County"},
    {"zip": "07407", "city": "Elmwood Park", "county": "Bergen County"},
    {"zip": "08731", "city": "Forked River", "county": "Ocean County"},
    {"zip": "07871", "city": "Sparta", "county": "Sussex County"},
    {"zip": "08550", "city": "Princeton Junction", "county": "Mercer County"},
    {"zip": "08057", "city": "Moorestown", "county": "Burlington County"},
    {"zip": "07095", "city": "Woodbridge", "county": "Middlesex County"},
    {"zip": "08536", "city": "Plainsboro", "county": "Middlesex County"},
    {"zip": "08077", "city": "Riverton", "county": "Burlington County"},
    {"zip": "08232", "city": "Pleasantville", "county": "Atlantic County"},
    {"zip": "07650", "city": "Palisades Park", "county": "Bergen County"},
    {"zip": "08690", "city": "Trenton", "county": "Mercer County"},
    {"zip": "08052", "city": "Maple Shade", "county": "Burlington County"},
    {"zip": "08034", "city": "Cherry Hill", "county": "Camden County"},
    {"zip": "07503", "city": "Paterson", "county": "Passaic County"},
    {"zip": "08872", "city": "Sayreville", "county": "Middlesex County"},
    {"zip": "07928", "city": "Chatham", "county": "Morris County"},
    {"zip": "08837", "city": "Edison", "county": "Middlesex County"},
    {"zip": "08110", "city": "Pennsauken", "county": "Camden County"},
    {"zip": "07506", "city": "Hawthorne", "county": "Passaic County"},
    {"zip": "07735", "city": "Keyport", "county": "Monmouth County"},
    {"zip": "08015", "city": "Browns Mills", "county": "Burlington County"},
    {"zip": "08108", "city": "Collingswood", "county": "Camden County"},
    {"zip": "08361", "city": "Vineland", "county": "Cumberland County"},
    {"zip": "07070", "city": "Rutherford", "county": "Bergen County"},
    {"zip": "07079", "city": "South Orange", "county": "Essex County"},
    {"zip": "07067", "city": "Colonia", "county": "Middlesex County"},
    {"zip": "08830", "city": "Iselin", "county": "Middlesex County"},
    {"zip": "07514", "city": "Paterson", "county": "Passaic County"},
    {"zip": "07461", "city": "Sussex", "county": "Sussex County"},
    {"zip": "07746", "city": "Marlboro", "county": "Monmouth County"},
    {"zip": "08840", "city": "Metuchen", "county": "Middlesex County"},
    {"zip": "08852", "city": "Monmouth Junction", "county": "Middlesex County"},
    {"zip": "08505", "city": "Bordentown", "county": "Burlington County"},
    {"zip": "07834", "city": "Denville", "county": "Morris County"},
    {"zip": "07628", "city": "Dumont", "county": "Bergen County"},
    {"zip": "07405", "city": "Butler", "county": "Morris County"},
    {"zip": "08062", "city": "Mullica Hill", "county": "Gloucester County"},
    {"zip": "07940", "city": "Madison", "county": "Morris County"},
    {"zip": "08204", "city": "Cape May", "county": "Cape May County"},
    {"zip": "08210", "city": "Cape May Court House", "county": "Cape May County"},
    {"zip": "07502", "city": "Paterson", "county": "Passaic County"},
    {"zip": "07001", "city": "Avenel", "county": "Middlesex County"},
    {"zip": "07733", "city": "Holmdel", "county": "Monmouth County"},
    {"zip": "08033", "city": "Haddonfield", "county": "Camden County"},
    {"zip": "07081", "city": "Springfield", "county": "Union County"},
    {"zip": "08691", "city": "Robbinsville", "county": "Mercer County"},
    {"zip": "07646", "city": "New Milford", "county": "Bergen County"},
    {"zip": "07481", "city": "Wyckoff", "county": "Bergen County"},
    {"zip": "07086", "city": "Weehawken", "county": "Hudson County"},
    {"zip": "07730", "city": "Hazlet", "county": "Monmouth County"},
    {"zip": "07031", "city": "North Arlington", "county": "Bergen County"},
    {"zip": "07059", "city": "Warren", "county": "Somerset County"},
    {"zip": "08882", "city": "South River", "county": "Middlesex County"},
    {"zip": "07066", "city": "Clark", "county": "Union County"},
    {"zip": "07670", "city": "Tenafly", "county": "Bergen County"},
    {"zip": "07524", "city": "Paterson", "county": "Passaic County"},
    {"zip": "07005", "city": "Boonton", "county": "Morris County"},
    {"zip": "08904", "city": "Highland Park", "county": "Middlesex County"},
    {"zip": "07022", "city": "Fairview", "county": "Bergen County"},
    {"zip": "07480", "city": "West Milford", "county": "Passaic County"},
    {"zip": "07012", "city": "Clifton", "county": "Passaic County"},
    {"zip": "07063", "city": "Plainfield", "county": "Union County"},
    {"zip": "07446", "city": "Ramsey", "county": "Bergen County"},
    {"zip": "07882", "city": "Washington", "county": "Warren County"},
    {"zip": "08846", "city": "Middlesex", "county": "Middlesex County"},
    {"zip": "08009", "city": "Berlin", "county": "Camden County"},
    {"zip": "07044", "city": "Verona", "county": "Essex County"},
    {"zip": "07020", "city": "Edgewater", "county": "Bergen County"},
    {"zip": "07310", "city": "Jersey City", "county": "Hudson County"},
    {"zip": "07663", "city": "Saddle Brook", "county": "Bergen County"},
    {"zip": "07078", "city": "Short Hills", "county": "Essex County"},
    {"zip": "07062", "city": "Plainfield", "county": "Union County"},
    {"zip": "08805", "city": "Bound Brook", "county": "Somerset County"},
    {"zip": "07828", "city": "Budd Lake", "county": "Morris County"},
    {"zip": "08812", "city": "Dunellen", "county": "Somerset County"},
    {"zip": "07204", "city": "Roselle Park", "county": "Union County"},
    {"zip": "08215", "city": "Egg Harbor City", "county": "Atlantic County"},
    {"zip": "07504", "city": "Paterson", "county": "Passaic County"},
    {"zip": "08107", "city": "Oaklyn", "county": "Camden County"},
    {"zip": "07734", "city": "Keansburg", "county": "Monmouth County"},
    {"zip": "07102", "city": "Newark", "county": "Essex County"},
    {"zip": "07043", "city": "Montclair", "county": "Essex County"},
    {"zip": "08069", "city": "Penns Grove", "county": "Salem County"},
    {"zip": "08824", "city": "Kendall Park", "county": "Middlesex County"},
    {"zip": "08030", "city": "Gloucester City", "county": "Camden County"},
    {"zip": "08736", "city": "Manasquan", "county": "Monmouth County"},
    {"zip": "07009", "city": "Cedar Grove", "county": "Essex County"},
    {"zip": "07660", "city": "Ridgefield Park", "county": "Bergen County"},
    {"zip": "07114", "city": "Newark", "county": "Essex County"},
    {"zip": "08629", "city": "Trenton", "county": "Mercer County"},
    {"zip": "08534", "city": "Pennington", "county": "Mercer County"},
    {"zip": "08620", "city": "Trenton", "county": "Mercer County"},
    {"zip": "07974", "city": "New Providence", "county": "Union County"},
    {"zip": "08609", "city": "Trenton", "county": "Mercer County"},
    {"zip": "08048", "city": "Lumberton", "county": "Burlington County"},
    {"zip": "07436", "city": "Oakland", "county": "Bergen County"},
    {"zip": "08103", "city": "Camden", "county": "Camden County"},
    {"zip": "08260", "city": "Wildwood", "county": "Cape May County"},
    {"zip": "08863", "city": "Fords", "county": "Middlesex County"},
    {"zip": "07853", "city": "Long Valley", "county": "Morris County"},
    {"zip": "08512", "city": "Cranbury", "county": "Middlesex County"},
    {"zip": "08070", "city": "Pennsville", "county": "Salem County"},
    {"zip": "08051", "city": "Mantua", "county": "Gloucester County"},
    {"zip": "07452", "city": "Glen Rock", "county": "Bergen County"},
    {"zip": "07604", "city": "Hasbrouck Heights", "county": "Bergen County"},
    {"zip": "07922", "city": "Berkeley Heights", "county": "Union County"},
    {"zip": "08318", "city": "Elmer", "county": "Salem County"},
    {"zip": "07836", "city": "Flanders", "county": "Morris County"},
    {"zip": "07661", "city": "River Edge", "county": "Bergen County"},
    {"zip": "07057", "city": "Wallington", "county": "Bergen County"},
    {"zip": "07456", "city": "Ringwood", "county": "Passaic County"},
    {"zip": "08031", "city": "Bellmawr", "county": "Camden County"},
    {"zip": "07458", "city": "Saddle River", "county": "Bergen County"},
    {"zip": "07885", "city": "Wharton", "county": "Morris County"},
    {"zip": "08502", "city": "Belle Mead", "county": "Somerset County"},
    {"zip": "07657", "city": "Ridgefield", "county": "Bergen County"},
    {"zip": "08010", "city": "Beverly", "county": "Burlington County"},
    {"zip": "08226", "city": "Ocean City", "county": "Cape May County"},
    {"zip": "07438", "city": "Oak Ridge", "county": "Morris County"},
    {"zip": "07843", "city": "Hopatcong", "county": "Sussex County"},
    {"zip": "07936", "city": "East Hanover", "county": "Morris County"},
    {"zip": "07513", "city": "Paterson", "county": "Passaic County"},
    {"zip": "07442", "city": "Pompton Lakes", "county": "Passaic County"},
    {"zip": "07417", "city": "Franklin Lakes", "county": "Bergen County"},
    {"zip": "07512", "city": "Totowa", "county": "Passaic County"},
    {"zip": "08004", "city": "Atco", "county": "Camden County"},
    {"zip": "07643", "city": "Little Ferry", "county": "Bergen County"},
    {"zip": "07444", "city": "Pompton Plains", "county": "Morris County"},
    {"zip": "07932", "city": "Florham Park", "county": "Morris County"},
    {"zip": "08722", "city": "Beachwood", "county": "Ocean County"},
    {"zip": "07035", "city": "Lincoln Park", "county": "Morris County"},
    {"zip": "08835", "city": "Manville", "county": "Somerset County"},
    {"zip": "08244", "city": "Somers Point", "county": "Atlantic County"},
    {"zip": "08079", "city": "Salem", "county": "Salem County"},
    {"zip": "08889", "city": "Whitehouse Station", "county": "Hunterdon County"},
    {"zip": "08322", "city": "Franklinville", "county": "Gloucester County"},
    {"zip": "08251", "city": "Villas", "county": "Cape May County"},
    {"zip": "07045", "city": "Montville", "county": "Morris County"},
    {"zip": "07642", "city": "Hillsdale", "county": "Bergen County"},
    {"zip": "08201", "city": "Absecon", "county": "Atlantic County"},
    {"zip": "07463", "city": "Waldwick", "county": "Bergen County"},
    {"zip": "07034", "city": "Lake Hiawatha", "county": "Morris County"},
    {"zip": "07607", "city": "Maywood", "county": "Bergen County"},
    {"zip": "07073", "city": "East Rutherford", "county": "Bergen County"},
    {"zip": "07722", "city": "Colts Neck", "county": "Monmouth County"},
    {"zip": "07075", "city": "Wood Ridge", "county": "Bergen County"},
    {"zip": "07419", "city": "Hamburg", "county": "Sussex County"},
    {"zip": "08090", "city": "Wenonah", "county": "Gloucester County"},
    {"zip": "08106", "city": "Audubon", "county": "Camden County"},
    {"zip": "07825", "city": "Blairstown", "county": "Warren County"},
    {"zip": "07945", "city": "Mendham", "county": "Morris County"},
    {"zip": "08093", "city": "Westville", "county": "Gloucester County"},
    {"zip": "07760", "city": "Rumson", "county": "Monmouth County"},
    {"zip": "07821", "city": "Andover", "county": "Sussex County"},
    {"zip": "07876", "city": "Succasunna", "county": "Morris County"},
    {"zip": "08098", "city": "Woodstown", "county": "Salem County"},
    {"zip": "08083", "city": "Somerdale", "county": "Camden County"},
    {"zip": "08071", "city": "Pitman", "county": "Gloucester County"},
    {"zip": "07605", "city": "Leonia", "county": "Bergen County"},
    {"zip": "07676", "city": "Township Of Washington", "county": "Bergen County"},
    {"zip": "08022", "city": "Columbus", "county": "Burlington County"},
    {"zip": "08628", "city": "Trenton", "county": "Mercer County"},
    {"zip": "07626", "city": "Cresskill", "county": "Bergen County"},
    {"zip": "07656", "city": "Park Ridge", "county": "Bergen County"},
    {"zip": "08833", "city": "Lebanon", "county": "Hunterdon County"},
    {"zip": "08406", "city": "Ventnor City", "county": "Atlantic County"},
    {"zip": "08823", "city": "Franklin Park", "county": "Somerset County"},
    {"zip": "07603", "city": "Bogota", "county": "Bergen County"},
    {"zip": "07981", "city": "Whippany", "county": "Morris County"},
    {"zip": "07849", "city": "Lake Hopatcong", "county": "Morris County"},
    {"zip": "07624", "city": "Closter", "county": "Bergen County"},
    {"zip": "07764", "city": "West Long Branch", "county": "Monmouth County"},
    {"zip": "07874", "city": "Stanhope", "county": "Sussex County"},
    {"zip": "08312", "city": "Clayton", "county": "Gloucester County"},
    {"zip": "08225", "city": "Northfield", "county": "Atlantic County"},
    {"zip": "08102", "city": "Camden", "county": "Camden County"},
    {"zip": "07645", "city": "Montvale", "county": "Bergen County"},
    {"zip": "08850", "city": "Milltown", "county": "Middlesex County"},
    {"zip": "08810", "city": "Dayton", "county": "Middlesex County"},
    {"zip": "07033", "city": "Kenilworth", "county": "Union County"},
    {"zip": "08869", "city": "Raritan", "county": "Somerset County"},
    {"zip": "08848", "city": "Milford", "county": "Hunterdon County"},
    {"zip": "07716", "city": "Atlantic Highlands", "county": "Monmouth County"},
    {"zip": "08270", "city": "Woodbine", "county": "Cape May County"},
    {"zip": "07649", "city": "Oradell", "county": "Bergen County"},
    {"zip": "07762", "city": "Spring Lake", "county": "Monmouth County"},
    {"zip": "08884", "city": "Spotswood", "county": "Middlesex County"},
    {"zip": "07930", "city": "Chester", "county": "Morris County"},
    {"zip": "08086", "city": "Thorofare", "county": "Gloucester County"},
    {"zip": "08530", "city": "Lambertville", "county": "Hunterdon County"},
    {"zip": "08078", "city": "Runnemede", "county": "Camden County"},
    {"zip": "07028", "city": "Glen Ridge", "county": "Essex County"},
    {"zip": "08758", "city": "Waretown", "county": "Ocean County"},
    {"zip": "08066", "city": "Paulsboro", "county": "Gloucester County"},
    {"zip": "08515", "city": "Chesterfield", "county": "Burlington County"},
    {"zip": "08203", "city": "Brigantine", "county": "Atlantic County"},
    {"zip": "08640", "city": "Joint Base Mdl", "county": "Burlington County"},
    {"zip": "07830", "city": "Califon", "county": "Hunterdon County"},
    {"zip": "07924", "city": "Bernardsville", "county": "Somerset County"},
    {"zip": "07403", "city": "Bloomingdale", "county": "Passaic County"},
    {"zip": "07004", "city": "Fairfield", "county": "Essex County"},
    {"zip": "07023", "city": "Fanwood", "county": "Union County"},
    {"zip": "08734", "city": "Lanoka Harbor", "county": "Ocean County"},
    {"zip": "08801", "city": "Annandale", "county": "Hunterdon County"},
    {"zip": "07823", "city": "Belvidere", "county": "Warren County"},
    {"zip": "07921", "city": "Bedminster", "county": "Somerset County"},
    {"zip": "08035", "city": "Haddon Heights", "county": "Camden County"},
    {"zip": "08558", "city": "Skillman", "county": "Somerset County"},
    {"zip": "08065", "city": "Palmyra", "county": "Burlington County"},
    {"zip": "07041", "city": "Millburn", "county": "Essex County"},
    {"zip": "07421", "city": "Hewitt", "county": "Passaic County"},
    {"zip": "07630", "city": "Emerson", "county": "Bergen County"},
    {"zip": "07850", "city": "Landing", "county": "Morris County"},
    {"zip": "08068", "city": "Pemberton", "county": "Burlington County"},
    {"zip": "07432", "city": "Midland Park", "county": "Bergen County"},
    {"zip": "08008", "city": "Beach Haven", "county": "Ocean County"},
    {"zip": "07092", "city": "Mountainside", "county": "Union County"},
    {"zip": "07727", "city": "Farmingdale", "county": "Monmouth County"},
    {"zip": "08886", "city": "Stewartsville", "county": "Warren County"},
    {"zip": "08084", "city": "Stratford", "county": "Camden County"},
    {"zip": "08221", "city": "Linwood", "county": "Atlantic County"},
    {"zip": "08809", "city": "Clinton", "county": "Hunterdon County"},
    {"zip": "07401", "city": "Allendale", "county": "Bergen County"},
    {"zip": "07738", "city": "Lincroft", "county": "Monmouth County"},
    {"zip": "07462", "city": "Vernon", "county": "Sussex County"},
    {"zip": "07718", "city": "Belford", "county": "Monmouth County"},
    {"zip": "07069", "city": "Watchung", "county": "Somerset County"},
    {"zip": "07755", "city": "Oakhurst", "county": "Monmouth County"},
    {"zip": "08501", "city": "Allentown", "county": "Monmouth County"},
    {"zip": "07072", "city": "Carlstadt", "county": "Bergen County"},
    {"zip": "07068", "city": "Roseland", "county": "Essex County"},
    {"zip": "07704", "city": "Fair Haven", "county": "Monmouth County"},
    {"zip": "08533", "city": "New Egypt", "county": "Ocean County"},
    {"zip": "08230", "city": "Ocean View", "county": "Cape May County"},
    {"zip": "07757", "city": "Oceanport", "county": "Monmouth County"},
    {"zip": "07739", "city": "Little Silver", "county": "Monmouth County"},
    {"zip": "07677", "city": "Woodcliff Lake", "county": "Bergen County"},
    {"zip": "07058", "city": "Pine Brook", "county": "Morris County"},
    {"zip": "07465", "city": "Wanaque", "county": "Passaic County"},
    {"zip": "08036", "city": "Hainesport", "county": "Burlington County"},
    {"zip": "08091", "city": "West Berlin", "county": "Camden County"},
    {"zip": "08029", "city": "Glendora", "county": "Camden County"},
    {"zip": "08867", "city": "Pittstown", "county": "Hunterdon County"},
    {"zip": "07662", "city": "Rochelle Park", "county": "Bergen County"},
    {"zip": "08551", "city": "Ringoes", "county": "Hunterdon County"},
    {"zip": "07416", "city": "Franklin", "county": "Sussex County"},
    {"zip": "08518", "city": "Florence", "county": "Burlington County"},
    {"zip": "07648", "city": "Norwood", "county": "Bergen County"},
    {"zip": "07082", "city": "Towaco", "county": "Morris County"},
    {"zip": "08514", "city": "Cream Ridge", "county": "Monmouth County"},
    {"zip": "08007", "city": "Barrington", "county": "Camden County"},
    {"zip": "07826", "city": "Branchville", "county": "Sussex County"},
    {"zip": "08059", "city": "Mount Ephraim", "county": "Camden County"},
    {"zip": "08510", "city": "Millstone Township", "county": "Monmouth County"},
    {"zip": "08056", "city": "Mickleton", "county": "Gloucester County"},
    {"zip": "07422", "city": "Highland Lakes", "county": "Sussex County"},
    {"zip": "08853", "city": "Neshanic Station", "county": "Somerset County"},
    {"zip": "07632", "city": "Englewood Cliffs", "county": "Bergen County"},
    {"zip": "07647", "city": "Northvale", "county": "Bergen County"},
    {"zip": "08402", "city": "Margate City", "county": "Atlantic County"},
    {"zip": "08049", "city": "Magnolia", "county": "Camden County"},
    {"zip": "08826", "city": "Glen Gardner", "county": "Hunterdon County"},
    {"zip": "07420", "city": "Haskell", "county": "Passaic County"},
    {"zip": "08730", "city": "Brielle", "county": "Monmouth County"},
    {"zip": "07627", "city": "Demarest", "county": "Bergen County"},
    {"zip": "08027", "city": "Gibbstown", "county": "Gloucester County"},
    {"zip": "08559", "city": "Stockton", "county": "Hunterdon County"},
    {"zip": "08641", "city": "Joint Base Mdl", "county": "Burlington County"},
    {"zip": "08343", "city": "Monroeville", "county": "Salem County"},
    {"zip": "08535", "city": "Millstone Township", "county": "Monmouth County"},
    {"zip": "08880", "city": "South Bound Brook", "county": "Somerset County"},
    {"zip": "07640", "city": "Harrington Park", "county": "Bergen County"},
    {"zip": "08344", "city": "Newfield", "county": "Gloucester County"},
    {"zip": "07732", "city": "Highlands", "county": "Monmouth County"},
    {"zip": "07440", "city": "Pequannock", "county": "Morris County"},
    {"zip": "07505", "city": "Paterson", "county": "Passaic County"},
    {"zip": "08825", "city": "Frenchtown", "county": "Hunterdon County"},
    {"zip": "08525", "city": "Hopewell", "county": "Mercer County"},
    {"zip": "07027", "city": "Garwood", "county": "Union County"},
    {"zip": "08544", "city": "Princeton", "county": "Mercer County"},
    {"zip": "07046", "city": "Mountain Lakes", "county": "Morris County"},
    {"zip": "07758", "city": "Port Monmouth", "county": "Monmouth County"},
    {"zip": "07856", "city": "Mount Arlington", "county": "Morris County"},
    {"zip": "07848", "city": "Lafayette", "county": "Sussex County"},
    {"zip": "08802", "city": "Asbury", "county": "Hunterdon County"},
    {"zip": "07423", "city": "Ho Ho Kus", "county": "Bergen County"},
    {"zip": "08223", "city": "Marmora", "county": "Cape May County"},
    {"zip": "08554", "city": "Roebling", "county": "Burlington County"},
    {"zip": "07737", "city": "Leonardo", "county": "Monmouth County"},
    {"zip": "07927", "city": "Cedar Knolls", "county": "Morris County"},
    {"zip": "08089", "city": "Waterford Works", "county": "Camden County"},
    {"zip": "07720", "city": "Bradley Beach", "county": "Monmouth County"},
    {"zip": "07702", "city": "Shrewsbury", "county": "Monmouth County"},
    {"zip": "07827", "city": "Montague", "county": "Sussex County"},
    {"zip": "07014", "city": "Clifton", "county": "Passaic County"},
    {"zip": "07852", "city": "Ledgewood", "county": "Morris County"},
    {"zip": "07457", "city": "Riverdale", "county": "Morris County"},
    {"zip": "07064", "city": "Port Reading", "county": "Middlesex County"},
    {"zip": "08836", "city": "Martinsville", "county": "Somerset County"},
    {"zip": "07803", "city": "Mine Hill", "county": "Morris County"},
    {"zip": "08562", "city": "Wrightstown", "county": "Burlington County"},
    {"zip": "07721", "city": "Cliffwood", "county": "Monmouth County"},
    {"zip": "08327", "city": "Leesburg", "county": "Cumberland County"},
    {"zip": "08735", "city": "Lavallette", "county": "Ocean County"},
    {"zip": "08242", "city": "Rio Grande", "county": "Cape May County"},
    {"zip": "08827", "city": "Hampton", "county": "Hunterdon County"},
    {"zip": "08560", "city": "Titusville", "county": "Mercer County"},
    {"zip": "08750", "city": "Sea Girt", "county": "Monmouth County"},
    {"zip": "08751", "city": "Seaside Heights", "county": "Ocean County"},
    {"zip": "07863", "city": "Oxford", "county": "Warren County"},
    {"zip": "07857", "city": "Netcong", "county": "Morris County"},
    {"zip": "08829", "city": "High Bridge", "county": "Hunterdon County"},
    {"zip": "08061", "city": "Mount Royal", "county": "Gloucester County"},
    {"zip": "07931", "city": "Far Hills", "county": "Somerset County"},
    {"zip": "07641", "city": "Haworth", "county": "Bergen County"},
    {"zip": "07756", "city": "Ocean Grove", "county": "Monmouth County"},
    {"zip": "08097", "city": "Woodbury Heights", "county": "Gloucester County"},
    {"zip": "07750", "city": "Monmouth Beach", "county": "Monmouth County"},
    {"zip": "07838", "city": "Great Meadows", "county": "Warren County"},
    {"zip": "07832", "city": "Columbia", "county": "Warren County"},
    {"zip": "07460", "city": "Stockholm", "county": "Sussex County"},
    {"zip": "08804", "city": "Bloomsbury", "county": "Hunterdon County"},
    {"zip": "08092", "city": "West Creek", "county": "Ocean County"},
    {"zip": "07074", "city": "Moonachie", "county": "Bergen County"},
    {"zip": "08063", "city": "National Park", "county": "Gloucester County"},
    {"zip": "08045", "city": "Lawnside", "county": "Camden County"},
    {"zip": "07088", "city": "Vauxhall", "county": "Union County"},
    {"zip": "07946", "city": "Millington", "county": "Morris County"},
    {"zip": "07980", "city": "Stirling", "county": "Morris County"},
    {"zip": "08733", "city": "Lakehurst", "county": "Ocean County"},
    {"zip": "08240", "city": "Pomona", "county": "Atlantic County"},
    {"zip": "08020", "city": "Clarksboro", "county": "Gloucester County"},
    {"zip": "07606", "city": "South Hackensack", "county": "Bergen County"},
    {"zip": "08741", "city": "Pine Beach", "county": "Ocean County"},
    {"zip": "08832", "city": "Keasbey", "county": "Middlesex County"},
    {"zip": "07077", "city": "Sewaren", "county": "Middlesex County"},
    {"zip": "07933", "city": "Gillette", "county": "Morris County"},
    {"zip": "08542", "city": "Princeton", "county": "Mercer County"},
    {"zip": "07865", "city": "Port Murray", "county": "Warren County"},
    {"zip": "07418", "city": "Glenwood", "county": "Sussex County"},
    {"zip": "07435", "city": "Newfoundland", "county": "Passaic County"},
    {"zip": "08349", "city": "Port Norris", "county": "Cumberland County"},
    {"zip": "08752", "city": "Seaside Park", "county": "Ocean County"},
    {"zip": "08828", "city": "Helmetta", "county": "Middlesex County"},
    {"zip": "07021", "city": "Essex Fells", "county": "Essex County"},
    {"zip": "08341", "city": "Minotola", "county": "Atlantic County"},
    {"zip": "08026", "city": "Gibbsboro", "county": "Camden County"},
    {"zip": "07439", "city": "Ogdensburg", "county": "Sussex County"},
    {"zip": "08243", "city": "Sea Isle City", "county": "Cape May County"},
    {"zip": "07711", "city": "Allenhurst", "county": "Monmouth County"},
    {"zip": "07717", "city": "Avon By The Sea", "county": "Monmouth County"},
    {"zip": "07311", "city": "Jersey City", "county": "Hudson County"},
    {"zip": "07847", "city": "Kenvil", "county": "Morris County"},
    {"zip": "08740", "city": "Ocean Gate", "county": "Ocean County"},
    {"zip": "08067", "city": "Pedricktown", "county": "Salem County"},
    {"zip": "08202", "city": "Avalon", "county": "Cape May County"},
    {"zip": "08311", "city": "Cedarville", "county": "Cumberland County"},
    {"zip": "07934", "city": "Gladstone", "county": "Somerset County"},
    {"zip": "08328", "city": "Malaga", "county": "Gloucester County"},
    {"zip": "07620", "city": "Alpine", "county": "Bergen County"},
    {"zip": "08732", "city": "Island Heights", "county": "Ocean County"},
    {"zip": "08738", "city": "Mantoloking", "county": "Ocean County"},
    {"zip": "08887", "city": "Three Bridges", "county": "Hunterdon County"},
    {"zip": "08319", "city": "Estell Manor", "county": "Atlantic County"},
    {"zip": "08317", "city": "Dorothy", "county": "Atlantic County"},
    {"zip": "08326", "city": "Landisville", "county": "Atlantic County"},
    {"zip": "08320", "city": "Fairton", "county": "Cumberland County"},
    {"zip": "08555", "city": "Roosevelt", "county": "Monmouth County"},
    {"zip": "08241", "city": "Port Republic", "county": "Atlantic County"},
    {"zip": "08310", "city": "Buena", "county": "Atlantic County"},
    {"zip": "08247", "city": "Stone Harbor", "county": "Cape May County"},
    {"zip": "07822", "city": "Augusta", "county": "Sussex County"},
    {"zip": "08019", "city": "Chatsworth", "county": "Burlington County"},
    {"zip": "08403", "city": "Longport", "county": "Atlantic County"},
    {"zip": "08340", "city": "Milmay", "county": "Cumberland County"},
    {"zip": "08511", "city": "Cookstown", "county": "Burlington County"},
    {"zip": "08001", "city": "Alloway", "county": "Salem County"},
    {"zip": "08041", "city": "Jobstown", "county": "Burlington County"},
    {"zip": "08553", "city": "Rocky Hill", "county": "Somerset County"},
    {"zip": "08608", "city": "Trenton", "county": "Mercer County"},
    {"zip": "07878", "city": "Mount Tabor", "county": "Morris County"},
    {"zip": "07723", "city": "Deal", "county": "Monmouth County"},
    {"zip": "08345", "city": "Newport", "county": "Cumberland County"},
    {"zip": "07977", "city": "Peapack", "county": "Somerset County"},
    {"zip": "08323", "city": "Greenwich", "county": "Cumberland County"},
    {"zip": "08720", "city": "Allenwood", "county": "Monmouth County"},
    {"zip": "08314", "city": "Delmont", "county": "Cumberland County"},
    {"zip": "08350", "city": "Richland", "county": "Atlantic County"},
    {"zip": "08821", "city": "Flagtown", "county": "Somerset County"},
    {"zip": "07935", "city": "Green Village", "county": "Morris County"},
    {"zip": "08006", "city": "Barnegat Light", "county": "Ocean County"},
    {"zip": "08346", "city": "Newtonville", "county": "Atlantic County"},
    {"zip": "08352", "city": "Rosenhayn", "county": "Cumberland County"},
    {"zip": "08038", "city": "Hancocks Bridge", "county": "Salem County"},
    {"zip": "07851", "city": "Layton", "county": "Sussex County"},
    {"zip": "07880", "city": "Vienna", "county": "Warren County"},
    {"zip": "07976", "city": "New Vernon", "county": "Morris County"},
    {"zip": "07961", "city": "Convent Station", "county": "Morris County"},
    {"zip": "07939", "city": "Lyons", "county": "Somerset County"},
    {"zip": "08561", "city": "Windsor", "county": "Mercer County"},
    {"zip": "08324", "city": "Heislerville", "county": "Cumberland County"},
    {"zip": "08329", "city": "Mauricetown", "county": "Cumberland County"},
    {"zip": "08353", "city": "Shiloh", "county": "Cumberland County"},
    {"zip": "08014", "city": "Bridgeport", "county": "Gloucester County"},
    {"zip": "08023", "city": "Deepwater", "county": "Salem County"},
    {"zip": "07970", "city": "Mount Freedom", "county": "Morris County"},
    {"zip": "08072", "city": "Quinton", "county": "Salem County"},
    {"zip": "07979", "city": "Pottersville", "county": "Hunterdon County"},
    {"zip": "08032", "city": "Grenloch", "county": "Gloucester County"},
    {"zip": "08348", "city": "Port Elizabeth", "county": "Cumberland County"},
    {"zip": "08224", "city": "New Gretna", "county": "Burlington County"},
    {"zip": "08316", "city": "Dorchester", "county": "Cumberland County"},
    {"zip": "08528", "city": "Kingston", "county": "Somerset County"},
    {"zip": "08212", "city": "Cape May Point", "county": "Cape May County"},
    {"zip": "08248", "city": "Strathmere", "county": "Cape May County"},
    {"zip": "07833", "city": "Delaware", "county": "Warren County"},
    {"zip": "07844", "city": "Hope", "county": "Warren County"},
    {"zip": "08321", "city": "Fortescue", "county": "Cumberland County"},
    {"zip": "07608", "city": "Teterboro", "county": "Bergen County"},
    {"zip": "08890", "city": "Zarephath", "county": "Somerset County"},
    {"zip": "07926", "city": "Brookside", "county": "Morris County"},
    {"zip": "08064", "city": "New Lisbon", "county": "Burlington County"},
    {"zip": "08246", "city": "South Seaville", "county": "Cape May County"},
    {"zip": "08011", "city": "Birmingham", "county": "Burlington County"},
    {"zip": "08042", "city": "Juliustown", "county": "Burlington County"},
    {"zip": "07831", "city": "Changewater", "county": "Warren County"},
    {"zip": "07870", "city": "Schooleys Mountain", "county": "Morris County"},
    {"zip": "07846", "city": "Johnsonburg", "county": "Warren County"},
    {"zip": "08039", "city": "Harrisonville", "county": "Gloucester County"},
    {"zip": "07881", "city": "Wallpack Center", "county": "Sussex County"},
    {"zip": "07820", "city": "Allamuchy", "county": "Warren County"},
    {"zip": "07703", "city": "Fort Monmouth", "county": "Monmouth County"},
    {"zip": "07842", "city": "Hibernia", "county": "Morris County"},
    {"zip": "08073", "city": "Rancocas", "county": "Burlington County"},
    {"zip": "08074", "city": "Richwood", "county": "Gloucester County"},
    {"zip": "08095", "city": "Winslow", "county": "Camden County"},
    {"zip": "08217", "city": "Elwood", "county": "Atlantic County"},
    {"zip": "08245", "city": "South Dennis", "county": "Cape May County"},
    {"zip": "08858", "city": "Oldwick", "county": "Hunterdon County"}
]

def get_complete_nj_zipcodes():
    """Returns the complete list of 576 New Jersey ZIP codes"""
    return FULL_NJ_ZIP_LIST

print(f"📍 Complete NJ ZIP codes loaded: {len(FULL_NJ_ZIP_LIST)} ZIP codes")